// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtudictjjosqgpuawgkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10dWRpY3Rqam9zcWdwdWF3Z2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDA4NDcsImV4cCI6MjA2OTMxNjg0N30.Vvj3zYUgKVrUaC49WnnK-TuwU_2QZPK8V5aX-wdQ2YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});